Overloaded get_songs and added tests
res0nance/darklyrics pull request #7
Opened 2018-12-13 19:33 UTC by jakeHebert

I overloaded get_songs() to allow users to return an array of songs for a specific album instead of all songs across their discography. I also updated the test file to test the overloaded function.

2018-12-13 19:45 UTC, jakeHebert commented
The test seems to be failing because python 3.5 couldn't install for the Travis CI build...

2019-01-25 05:25 UTC, res0nance requested changes

2019-01-25 05:25 UTC, res0nance commented on darklyrics/darklyrics.py
> +        url = get_artist_url(artist)
```
url = get_artist_url(artist)
        response = requests.get(url)
        soup = BeautifulSoup(response.content, 'html.parser')
        if 'not Found' in soup.title.string:
            raise LyricsNotFound()
```
This bit is repeated try moving it before the if

2019-01-30 17:37 UTC, jakeHebert commented on darklyrics/darklyrics.py
> +        url = get_artist_url(artist)
Good catch! Gonna fix that bit.

2019-02-04 14:36 UTC, res0nance requested changes

2019-02-04 14:36 UTC, res0nance commented on darklyrics/darklyrics.py
> +        result = []
These bunch of lines are repeated as well

2019-02-15 16:09 UTC, res0nance approved these changes
👍 Nice and clean

2019-02-15 16:09 UTC, merged